-- EXECICIO 2 - 2

SELECT COUNT(*) FROM pacientes;
SELECT COUNT(*) FROM pacientes WHERE "IC_SEXO" = 'M';
SELECT COUNT(*) FROM pacientes WHERE "IC_SEXO" = 'F';

SELECT ( (2021-MIN("AA_NASCIMENTO")) - (2021-MAX("AA_NASCIMENTO"))) AS amplitude,
(2021-MIN("AA_NASCIMENTO")) AS velho,
(2021-MAX("AA_NASCIMENTO")) AS novo
FROM pacientes WHERE "IC_SEXO" = 'M';
SELECT ( (2021-MIN("AA_NASCIMENTO")) - (2021-MAX("AA_NASCIMENTO"))) AS amplitude,
(2021-MIN("AA_NASCIMENTO")) AS velho,
(2021-MAX("AA_NASCIMENTO")) AS novo
FROM pacientes WHERE "IC_SEXO" = 'F';

SELECT
(2021 - MAX("AA_NASCIMENTO")) AS minimo,
(2021 - PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY "AA_NASCIMENTO")) AS Q1,
(2021 - PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "AA_NASCIMENTO")) AS Q2Median,
(2021 - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY "AA_NASCIMENTO")) AS Q3,
(2021 - MIN("AA_NASCIMENTO")) AS maximo
FROM pacientes;

SELECT 
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 2020 AND "AA_NASCIMENTO" > (2010))   AS "1-10",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 2010 AND "AA_NASCIMENTO" > (2000))   AS "10-20",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 2000 AND "AA_NASCIMENTO" > (1990))   AS "20-30",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 1990 AND "AA_NASCIMENTO" > (1980))   AS "30-40",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 1980 AND "AA_NASCIMENTO" > (1970))   AS "40-50",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 1970 AND "AA_NASCIMENTO" > (1960))   AS "50-60",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 1960 AND "AA_NASCIMENTO" > (1950))   AS "60-70",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 1950 AND "AA_NASCIMENTO" > (1940))   AS "70-80",
COUNT(*) FILTER (WHERE "AA_NASCIMENTO" <= 1940 AND "AA_NASCIMENTO" > (1930))   AS "80-90"
FROM pacientes;

SELECT "ID_PACIENTE",
	COUNT(*) OVER(Partition by "ID_PACIENTE") Qtd
FROM exames
Order by Qtd DESC;




