WITH M AS (SELECT "ID_PACIENTE", "DT_COLETA", "DE_ANALITO", Avg(REPLACE("DE_RESULTADO", ',','.')::DECIMAL) from exames
WHERE ("DE_EXAME" LIKE '%Colesterol%')
AND "DE_RESULTADO" ~ '^[0-9\.\,]+$'
GROUP BY "ID_PACIENTE", "DT_COLETA", "DE_ANALITO", "DE_RESULTADO")

SELECT "ID_PACIENTE", "DT_COLETA",
MAX((CASE  WHEN "DE_ANALITO"='HDL-Colesterol' OR "DE_ANALITO"='Hdl-Colesterol' THEN avg ELSE 0 END)) AS "HDL",
MAX((CASE  WHEN "DE_ANALITO"='VLDL-Colesterol' OR "DE_ANALITO"='V-Colesterol' THEN avg ELSE 0 END)) AS "VLDL",
MAX((CASE  WHEN "DE_ANALITO"='LDL Colesterol' THEN avg ELSE 0 END)) AS "LDL",
MAX((CASE  WHEN "DE_ANALITO"='Colesterol não-HDL, soro' THEN avg ELSE 0 END)) AS "Não HDL",
MAX((CASE  WHEN "DE_ANALITO"='Colesterol total' THEN avg ELSE 0 END)) AS "Total"
FROM M 
GROUP BY "ID_PACIENTE", "DT_COLETA";