WITH M AS (SELECT "ID_PACIENTE", "DT_COLETA", "DE_ANALITO", Avg(REPLACE("DE_RESULTADO", ',','.')::DECIMAL)::DECIMAL(10,2) AS "AVG", "ID_ATENDIMENTO" from exames
WHERE ("DE_EXAME" = 'Hemograma')
AND "DE_RESULTADO" ~ '^[1-9]\d*(\.\d+)?$'
GROUP BY "ID_PACIENTE", "ID_ATENDIMENTO", "DT_COLETA", "DE_ANALITO", "DE_RESULTADO")

SELECT M."ID_PACIENTE", "DT_COLETA",
MAX((CASE  WHEN "DE_ANALITO"='Basófilos' THEN "AVG" ELSE NULL END)) AS "BASOFILOS",
MAX((CASE  WHEN "DE_ANALITO"='Basófilos (%)' THEN "AVG" ELSE NULL END)) AS "BASOFILOS %",
MAX((CASE  WHEN "DE_ANALITO"='Bastonetes' THEN "AVG" ELSE NULL END)) AS "BASTONETES",
MAX((CASE  WHEN "DE_ANALITO"='Bastonetes (%)' THEN "AVG" ELSE NULL END)) AS "BASTONETES %",
MAX((CASE  WHEN "DE_ANALITO"='Blastos' THEN "AVG" ELSE NULL END)) AS "BLASTOS",
MAX((CASE  WHEN "DE_ANALITO"='Blastos (%)' THEN "AVG" ELSE NULL END)) AS "BLASTOS %",
MAX((CASE  WHEN "DE_ANALITO"='CHCM' THEN "AVG" ELSE NULL END)) AS "CHCM",
MAX((CASE  WHEN "DE_ANALITO"='Eosinófilos' THEN "AVG" ELSE NULL END)) AS "EOSINOFILOS",
MAX((CASE  WHEN "DE_ANALITO"='Eosinófilos (%)' THEN "AVG" ELSE NULL END)) AS "EOSINOFILOS %",
MAX((CASE  WHEN "DE_ANALITO"='Eritrócitos' THEN "AVG" ELSE NULL END)) AS "ERITROCITOS",
MAX((CASE  WHEN "DE_ANALITO"='Fração Imatura de Plaquetas' THEN "AVG" ELSE NULL END)) AS "FRACAO PLAQUETAS",
desfechos."DE_DESFECHO"
FROM M 
INNER JOIN desfechos ON desfechos."ID_ATENDIMENTO" = M."ID_ATENDIMENTO"
GROUP BY M."ID_PACIENTE", M."ID_ATENDIMENTO", "DT_COLETA", desfechos."DE_DESFECHO";