WITH M AS (SELECT "ID_PACIENTE", 
MIN((CASE  WHEN "DE_RESULTADO"='DETECTADO' OR "DE_RESULTADO"='DETECTADO (POSITIVO)'
	 OR "DE_RESULTADO"='DETECTÁVEL' OR "DE_RESULTADO"='POSITIVO' THEN "DT_COLETA" ELSE NULL END)) AS "DATA-POSITIVO",
MAX((CASE  WHEN "DE_RESULTADO"='Inconclusivo' OR "DE_RESULTADO"='INCONCLUSIVO'
	 OR "DE_RESULTADO"='INDETECTÁVEL' OR "DE_RESULTADO"='NÃO DETECTADO'
	 OR "DE_RESULTADO"='NÃO DETECTADO (NEGATIVO)' OR "DE_RESULTADO"='NEGATIVO' 
	 THEN "DT_COLETA" ELSE NULL END)) AS "DATA-NEGATIVO"
FROM exames
WHERE(LOWER("DE_ANALITO") LIKE '%ovid' OR LOWER("DE_ANALITO") LIKE '%oron%')
GROUP BY "ID_PACIENTE")

SELECT *, (CASE WHEN "DATA-POSITIVO" IS NOT NULL AND "DATA-NEGATIVO" IS NOT NULL 
		   THEN ABS("DATA-POSITIVO" - "DATA-NEGATIVO") ELSE NULL END) AS "INTERVALO (DIAS)"  FROM M
		   ORDER BY "INTERVALO (DIAS)";